-- Seed VCPC metric_catalog foundation.
insert into public.metric_catalog
(metric_code, product, industry, metric_name, metric_group, unit, value_type, aggregation_method, polarity, is_core, default_dimensions)
values
('revenue','both','general','Doanh thu','finance','VND','currency','sum','higher_is_better',true,'{}'),
('gross_profit','bizhealth','general','Lợi nhuận gộp','finance','VND','currency','sum','higher_is_better',true,'{}'),
('gross_margin_pct','bizhealth','general','Biên lợi nhuận gộp','finance','%','percent','avg','higher_is_better',true,'{}'),
('ebitda','bizhealth','general','EBITDA','finance','VND','currency','sum','higher_is_better',true,'{}'),
('ebitda_margin_pct','bizhealth','general','Biên EBITDA','finance','%','percent','avg','higher_is_better',true,'{}'),
('net_profit','bizhealth','general','Lợi nhuận sau thuế','finance','VND','currency','sum','higher_is_better',false,'{}'),
('marketing_cost','both','general','Chi phí marketing','cost','VND','currency','sum','lower_is_better',true,'{}'),
('marketing_cost_pct_revenue','both','general','Marketing / Doanh thu','cost','%','percent','avg','lower_is_better',true,'{}'),
('staff_cost','both','general','Chi phí nhân sự','cost','VND','currency','sum','lower_is_better',true,'{}'),
('rent_cost','both','general','Chi phí thuê mặt bằng','cost','VND','currency','sum','lower_is_better',false,'{}'),
('sga_cost_pct_revenue','bizhealth','general','SG&A / Doanh thu','cost','%','percent','avg','lower_is_better',true,'{}'),
('cash_balance','both','general','Số dư tiền','cashflow','VND','currency','last','higher_is_better',false,'{}'),
('cash_runway_days','both','general','Số ngày runway tiền mặt','cashflow','days','number','last','higher_is_better',true,'{}'),
('ar_days','bizhealth','general','Ngày phải thu','cashflow','days','number','avg','lower_is_better',false,'{}'),
('ap_days','bizhealth','general','Ngày phải trả','cashflow','days','number','avg','neutral',false,'{}'),
('inventory_days','both','general','Ngày tồn kho','operations','days','number','avg','lower_is_better',false,'{}'),
('customer_count','both','general','Số khách hàng','growth','count','count','sum','higher_is_better',false,'{}'),
('order_count','strategy_os','general','Số đơn hàng','growth','count','count','sum','higher_is_better',false,'{}'),
('branch_revenue','both','general','Doanh thu chi nhánh','branch','VND','currency','sum','higher_is_better',true,'{branch}'),
('branch_utilization','both','general','Công suất chi nhánh','branch','%','percent','avg','higher_is_better',true,'{branch}'),
('branch_customer_count','both','general','Số khách theo chi nhánh','branch','count','count','sum','higher_is_better',false,'{branch}'),
('product_revenue','strategy_os','general','Doanh thu sản phẩm/dịch vụ','product','VND','currency','sum','higher_is_better',false,'{product,category,channel}'),
('sku_units_sold','strategy_os','retail','Số lượng bán SKU','product','units','count','sum','higher_is_better',false,'{sku,category,channel}'),
('sell_through_rate','strategy_os','retail','Tỷ lệ bán qua','product','%','percent','avg','higher_is_better',false,'{sku,category}'),
('cac','both','general','Chi phí thu hút khách hàng','growth','VND','currency','avg','lower_is_better',false,'{channel}'),
('ltv','both','general','Giá trị vòng đời khách hàng','growth','VND','currency','avg','higher_is_better',false,'{channel,segment}'),
('repeat_rate','both','general','Tỷ lệ quay lại','growth','%','percent','avg','higher_is_better',false,'{}'),
('review_rating','strategy_os','general','Điểm đánh giá khách hàng','market_intelligence','score','number','avg','higher_is_better',false,'{platform,branch}'),
('competitor_new_branch_count','strategy_os','general','Số chi nhánh mới của đối thủ','market_intelligence','count','count','sum','neutral',false,'{competitor,location}'),
('top_selling_products_signal','strategy_os','retail','Tín hiệu top sản phẩm bán chạy','market_intelligence','json','json','custom','neutral',false,'{category,channel}')
on conflict (metric_code) do update set
  metric_name = excluded.metric_name,
  metric_group = excluded.metric_group,
  unit = excluded.unit,
  value_type = excluded.value_type,
  aggregation_method = excluded.aggregation_method,
  polarity = excluded.polarity,
  is_core = excluded.is_core,
  default_dimensions = excluded.default_dimensions,
  active = true,
  updated_at = public.vcpc_now_ms();
